Repository spacetelescope/spherical_geometry, pull requests merged in 2023-10, with the labels that each got.

#251 TST: Turn skip to xfail
  spherical_geometry/tests/test_intersection.py
Labels: bug, enhancement, Build wheels

#253 Replace numpy's inner1d with an alternative implementation
  CHANGES.rst
  spherical_geometry/great_circle_arc.py
  spherical_geometry/tests/test_basic.py
Labels: enhancement, maintenance

#254 Fix crash in convex_hull when input includes repeated points
  CHANGES.rst
  spherical_geometry/polygon.py
  spherical_geometry/tests/test_basic.py
  src/math_util.c
Labels: bug
