Repository spacetelescope/spherical_geometry, pull requests merged in 2024-05, with the labels that each got.

#267 Update README to reflect bundled qd
  README.rst
Labels: documentation

#270 Make math_util compatible with numpy 2.0
  pyproject.toml
  src/math_util.c
  tox.ini
Labels: maintenance

#265 Fix bugs in the Python implementation of inner1d and length
  CHANGES.rst
  pyproject.toml
  spherical_geometry/great_circle_arc.py
  spherical_geometry/polygon.py
  spherical_geometry/tests/test_basic.py
  spherical_geometry/tests/test_union.py
  src/math_util.c
Labels: bug, Build wheels

#271 Tox devdeps_npy2
  .github/workflows/spherical_geometry.yml
  tox.ini
Labels: Build wheels

#277 TST: Cancel duplicate wheel builds
  .github/workflows/publish-to-pypi.yml
Labels: Build wheels
