Repository spacetelescope/spherical_geometry, pull requests merged in 2025-01, with the labels that each got.

#281 require numpy released ver
  pyproject.toml
Labels: maintenance

#288 Fix failing unit test in Python 3.13
  CHANGES.rst
  spherical_geometry/tests/test_basic.py
  src/math_util.c
Labels: bug, Build wheels

#287 update minimum required versions, add 3.13
  .github/workflows/publish-to-pypi.yml
  .github/workflows/spherical_geometry.yml
  pyproject.toml
  tox.ini
Labels: maintenance, Build wheels

#289 update changelog comment
  CHANGES.rst
Labels: maintenance, Build wheels
